[build]
  publish = "hugoblog/public"
  command = "cd hugoblog && hugo --minify --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
