[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --minify --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[redirects]]
  from = "en/*"
  to = "en/404.html"
  status = 404

[[redirects]]
  from = "fr/*"
  to = "fr/404.html"
  status = 404