---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog Post
- type: document
  path: exampleSite/content/japanese/post/_index.md
  label: Blog Page (ja)
- type: document
  path: exampleSite/content/french/post/_index.md
  label: Blog Page (fr)
- type: directory
  path: exampleSite/content/japanese/post
  label: Post (ja)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: exampleSite/content/french/post
  label: Post (fr)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Author
- type: document
  path: exampleSite/content/japanese/author/_index.md
  label: Author Page (ja)
- type: document
  path: exampleSite/content/french/author/_index.md
  label: Author Page (fr)
- type: directory
  path: exampleSite/content/japanese/author
  label: Author (ja)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - author
- type: directory
  path: exampleSite/content/french/author
  label: Author (fr)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - author
- type: heading
  label: About
- type: document
  path: exampleSite/content/japanese/about-me.md
  label: About Me (ja)
- type: document
  path: exampleSite/content/french/about-me.md
  label: About Me (fr)
- type: document
  path: exampleSite/content/japanese/about-us.md
  label: About Us (ja)
- type: document
  path: exampleSite/content/french/about-us.md
  label: About Us (fr)
- type: heading
  label: Contact
- type: document
  path: exampleSite/content/japanese/contact.md
  label: Contact Page (ja)
- type: document
  path: exampleSite/content/french/contact.md
  label: Contact Page (fr)
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content/japanese
  label: All Page (ja)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/french
  label: All Page (fr)
  create: all
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite/i18n
  label: i18n Translations
  create: documents
  match: "**/*"
- type: document
  path: exampleSite/config.toml
  label: Configuration
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.74.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.74.3
