######################## default configuration ####################
baseURL = "https://menglish.jp/"
title = "Menglish  | 海外在住イラストレーターmeow(めお)のブログ、「みんぐりっしゅ」"
# post pagination
paginate = "12"
# post excerpt
summaryLength = "20"
DefaultContentLanguage = "ja"
# google analytics
googleAnalytics = "UA-74441948-2" # Ex: UA-123-45
# google adsense
adsensePublisher = "ca-pub-3482692642667396"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

############################# Output ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

# robots.txt
enableRobotsTXT = true

# site variables
[params.variables]
primary_color = "#41C9B4"
text_color = "#555"
text_color_dark = "#333"
text_color_light = "#777"
body_color = "#fff"
border_color = "#EBEBEB"
black = "#000"
white = "#fff"
light = "#F9F9F9"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
# primary_font = "Nunito Sans:wght@400;600;700;800"
primary_font = "Nunito Sans:ital,wght@0,400;0,600;0,700;0,800;1,800"
primary_font_type = "sans-serif" # [serif/sans-serif]
secondary_font = ""
secondary_font_type = "" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


#################### default parameters ################################
[params]
favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "130px"
menu_align = "center" # available option (left, right, or center )
AmazonID = "halflinger-22"
# Meta data
author = "Mao Miyamoto"
images = ["https://menglish.jp/images/backgrounds/header-bg.png"]
description = "海外在住イラストレーターmeow(めお)のブログ、「みんぐりっしゅ」"
# contact form action
contact_form_action = "https://formspree.io/f/xeqvgnzk" # contact form works with https://formspree.io
# Go to https://formspree.io, and create an account by click on signup button. Now verify your email address by click on varify button in the mail you got in your inbox. form action will looks like this contact_form_action = "https://formspree.io/your.name@email.com/" 

# search
search = true
# featured
featured_post = true
# layout
post_layout= "grid" # layout value (full, grid or list)
# Sidebar
sidebar = "right" # sidebar value (left, right or false)
# main taxonomy that will show at header and post card
main_taxonomy = "category" # optional value (tag or category)

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# Instagram feed
[params.instafeed]
enable = false
access_token = "" # place your instagram access token here

# promotion
[params.promotion]
title = "Create Stunning Website!!"
content = "Lorem ipsum dolor sit amet, consectetur sociis. Etiam nunc amet id dignissim. Feugiat id tempor vel sit ornare."
image = "images/promotion.jpg"
button_label = "Get Started"
button_link = "https://themefisher.com/"

# cookies
[params.cookies]
enable = true
expire_days = 2

# table of content
[markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

# related article
[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 10

######################## sidebar widgets #########################
[params.widgets]
sidebar = [ "about-me", "subscription", "categories", "recent-post", "tags"]
# available widget : search,about-me,authors,categories,tags,recent-post,social,promotion,subscription


############################# social site ########################

[[params.social]]
name = "twitter"
icon = "fab fa-twitter" # Fontawesome Icons : https://fontawesome.com/icons
link = "https://twitter.com/meeowmiya"



################################### Japanese language #####################################
[Languages.ja]
languageName = "Ja"
languageCode = "ja"
contentDir = "content/japanese"
weight = 1
heading = "Menglish"
subheading = "海外デザイナー<br>めおのブログ、<ミングリッシュ>"

[Languages.ja.about_me]
title = "Hi, I am meow!"
image = "images/author.png"
bio = "ボストン在住フリーランスイラストレーター。めおと読みます。フリーランス、英語、海外キャリア、ビザ、海外生活について書きます。"

############# japanese navigation ##############

# Dropdown menu
[[Languages.ja.menu.main]]
weight = 1
name = "home"
pre = "<i class='fas fa-home'></i>"
hasChildren = false

[[Languages.ja.menu.main]]
name = "フリーランス"
pre = "<i class='fas fa-laptop'></i>"
URL = "/tags/フリーランス"
weight = 2
  
[[Languages.ja.menu.main]]
name = " 海外で働く"
pre = "<i class='fa fa-globe-americas'></i>"
url = "/tags/海外で働く"
weight = 3

[[Languages.ja.menu.main]]
name = "英語"
pre = "<i class='far fa-comments'></i>"
url = "/tags/英語"
weight = 4

[[Languages.ja.menu.main]]
name = "プロフィール"
pre = "<i class='fas fa-user'></i>"
url = "about-me"
weight = 5


# footer menu
[[Languages.ja.menu.footer]]
name = "© 2021 Mao Miyamoto All rights reserved."
weight = 1

[[Languages.ja.menu.footer]]
name = "お問い合わせはこちら"
URL = "contact"
weight = 2

[[Languages.ja.menu.footer]]
name = "プライバシーポリシー"
URL = "privacy-policy"
weight = 3